#!/usr/bin/env bash
set -euo pipefail

BOLD=$'\033[1m'
GREEN=$'\033[32m'
YELLOW=$'\033[33m'
RED=$'\033[31m'
RESET=$'\033[0m'

OUTPUT="${1:-artifacts/ai/codebase.md}"
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

mkdir -p "$(dirname "$OUTPUT")"

FULL="$OUTPUT"
COMPACT="${OUTPUT%.md}.compact.md"

echo ""
echo "  ${BOLD}Generating AI context...${RESET}"
echo ""

run_gc() {
    local out="$1"

    if command -v gc >/dev/null 2>&1; then
        gc --output "$out"
        return $?
    fi

    if command -v npx >/dev/null 2>&1; then
        npx -y @iafahim/gc --output "$out"
        return $?
    fi

    return 1
}

manual_full() {
    local out="$1"

    {
        echo "# Codebase: $(basename "$ROOT")"
        echo ""
        echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo ""
        echo "## Files"
        echo ""
        find . \
            -path './.git' -prune -o \
            -path './bin' -prune -o \
            -path './obj' -prune -o \
            -path './artifacts' -prune -o \
            -path './.gameci' -prune -o \
            -type f -print | sort
        echo ""
        echo "## Important files"
        echo ""

        for f in \
            package.json \
            README.md \
            Directory.Build.props \
            __PACKAGE__.slnx \
            .github/workflows/ci.yml \
            .github/workflows/template-self-test.yml \
            .github/workflows/unity-package-test.yml \
            setup.sh \
            scripts/test-template.sh \
            scripts/validate-upm.sh \
            scripts/generate-ai-context.sh
        do
            if [ -f "$f" ]; then
                echo ""
                echo "### $f"
                echo '```'
                sed -n '1,240p' "$f"
                echo '```'
            fi
        done
    } > "$out"
}

manual_compact() {
    local out="$1"

    {
        echo "# Compact codebase summary"
        echo ""
        echo "## Package"
        python3 - <<'PY' 2>/dev/null || true
import json
with open("package.json", "r", encoding="utf-8") as f:
    data = json.load(f)
print(f"- name: {data.get('name')}")
print(f"- version: {data.get('version')}")
print(f"- unity: {data.get('unity')}")
print(f"- displayName: {data.get('displayName')}")
print(f"- dependencies: {data.get('dependencies', {})}")
PY
        echo ""
        echo "## Workflows"
        find .github/workflows -name '*.yml' -type f 2>/dev/null | sort
        echo ""
        echo "## Scripts"
        find scripts -maxdepth 1 -type f 2>/dev/null | sort
        echo ""
        echo "## Unity assemblies"
        find . -maxdepth 3 -name '*.asmdef' -type f 2>/dev/null | sort
    } > "$out"
}

if run_gc "$FULL"; then
    echo "  ${GREEN}✓${RESET} Full context generated by gc"
else
    echo "  ${YELLOW}⚠${RESET} gc unavailable or failed. Using manual fallback."
    manual_full "$FULL"
fi

if command -v gc >/dev/null 2>&1; then
    gc --brain --compress --output "$COMPACT" 2>/dev/null || manual_compact "$COMPACT"
else
    manual_compact "$COMPACT"
fi

if [ ! -s "$FULL" ]; then
    echo "  ${RED}✗${RESET} Missing or empty: $FULL"
    exit 1
fi

if [ ! -s "$COMPACT" ]; then
    echo "  ${RED}✗${RESET} Missing or empty: $COMPACT"
    exit 1
fi

echo "  ${GREEN}✓${RESET} AI context generated:"
echo "    $FULL"
echo "    $COMPACT"
echo ""
